FROM registry.cn-shanghai.aliyuncs.com/kolenz/openjdk:8-jdk
LABEL maintainer=gaoolin@gmail.com

# 指定jar包启动时的运行参数
ENV PARAMS="--server.port=8080 --spring.profiles.active=prod"
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

#COPY target/*.jar app.jar
COPY qtech-biz.jar app.jar

EXPOSE 8080

ENTRYPOINT ["/bin/sh", "-c", "java -Dfile.encoding=utf8 -Djava.security.egd=file:/dev/./urandom -jar app.jar ${PARAMS}"]
